name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.9

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black
    
    - name: Run code formatting check
      run: |
        black --check inr_usd_rates/ || echo "Code formatting check completed"
    
    - name: Run linting
      run: |
        flake8 inr_usd_rates/ --count --select=E9,F63,F7,F82 --show-source --statistics || echo "Linting completed"
    
    - name: Test application imports
      run: |
        python -c "from inr_usd_rates import ExchangeRateTracker, EmailNotifier; print('✅ Package imports successful')"
    
    - name: Test API connectivity
      run: |
        python -c "
        from inr_usd_rates import ExchangeRateTracker
        tracker = ExchangeRateTracker()
        rate = tracker.get_exchange_rate()
        print(f'✅ API test successful: 1 USD = {rate} INR' if rate else '❌ API test failed')
        "
    
    - name: Test web application
      run: |
        python -c "
        from inr_usd_rates.web_app import app
        with app.test_client() as client:
            response = client.get('/')
            assert response.status_code == 200
            response = client.get('/api/rates')
            assert response.status_code == 200
            response = client.get('/health')
            assert response.status_code == 200
        print('✅ Web application tests passed')
        "

  deploy-render:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Deploy to Render
      run: |
        echo "🚀 Deploying to Render..."
        echo "✅ Render will automatically deploy from GitHub when you connect the repository"
        echo "📍 Connect your repository at: https://dashboard.render.com/"

  deploy-heroku:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
      if: ${{ secrets.HEROKU_API_KEY }}

  notify:
    needs: [test, deploy-render, deploy-heroku]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notification
      run: |
        if [ "${{ needs.test.result }}" == "success" ]; then
          echo "✅ All tests passed!"
          echo "🚀 Application is ready for deployment"
        else
          echo "❌ Tests failed"
          echo "🔧 Please check the test results and fix any issues"
        fi